Repository WhistleGlobal/whistle-iOS, pull requests merged in 2023-09, with the labels that each got.

#9 [Feat] domainUrl Info.plist로 추가
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/xcshareddata/xcschemes/Whistle.xcscheme
  Whistle/Models/AppKeys.swift
  Whistle/Models/UserAuth.swift
  Whistle/Models/UserResponse.swift
  Whistle/UI/Components/SubmitButton.swift
  Whistle/UI/Screens/SignInView/SignInView.swift
  Whistle/ViewModels/AppleSignInViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#11 [Feat] 현재 어색한 애니메이션 수정 (프로필 화면 중단 탭 연타시 색상 버그, 하단 탭바 첫 실행시 포커스 가운데서 부터 시작)
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Components/ProfileTabItem.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
Labels: feat

#13 [Feat] FollowView 레이아웃 구현 , 기타 ProfileView 수정사항 적용
  Whistle.xcodeproj/project.pbxproj
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/Profile/FollowButtonStyle.swift
  Whistle/UI/Components/Profile/FollowTabbarStyle.swift
  Whistle/UI/Components/Profile/ProfileEditButtonStyle.swift
  Whistle/UI/Components/Profile/ProfileTabItem.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/Extension+UINavigationController.swift
Labels: feat

#15 [Fix] #Preview 코드 삭제
  Whistle/UI/Screens/Profile/FollowView.swift
Labels: fix

#17 [Feat] ProfileEditView 구현 (프로필 사진 업데이트는 추후 적용)
  Whistle.xcodeproj/project.pbxproj
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplictDark/Gray70_Dark.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/Profile/ProfileAlert.swift
  Whistle/UI/Components/Profile/ProfileToastMessage.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/WhistleApp.swift
Labels: feat

#19 [Feat] #18 Preview 코드 삭제
  Whistle/UI/Components/Profile/ProfileToastMessage.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/WhistleApp.swift
Labels: feat

#21 [Feat] MainView 레이아웃 구현
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/UserAuth.swift
  Whistle/Models/VideoModel.swift
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/Profile/FollowButtonStyle.swift
  Whistle/UI/Components/Profile/ProfileAlert.swift
  Whistle/UI/Components/Profile/ProfileEditButtonStyle.swift
  Whistle/UI/Components/Profile/ProfileToastMessage.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/Player.swift
  Whistle/UI/Screens/Main/PlayerPageView.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/ViewModels/AppleSignInViewModel.swift
  Whistle/ViewModels/VideoViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#23 [Feat] 프로필 사진 변경 레이아웃 구현 (사진 변경은 되지 않음, 커스텀 레이아웃 구현)
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/AlbumModel.swift
  Whistle/Models/PhotoModel.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/Profile/CustomAlbumListView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/ViewModels/PhotoViewModel.swift
Labels: feat

#25 [Feat] #24 이미지 변경 뷰 버그 수정 (이미지 변경 시 프리징 현상 수정)
  Whistle/UI/Screens/Profile/CustomAlbumListView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/ViewModels/PhotoViewModel.swift
Labels: feat

#27 [Feat] ProfileView API 통신 구현
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/Models/PhotoModel.swift
  Whistle/Models/Profile/BookMark.swift
  Whistle/Models/Profile/Follow.swift
  Whistle/Models/Profile/FollowUser.swift
  Whistle/Models/Profile/NotiSetting.swift
  Whistle/Models/Profile/PostFeed.swift
  Whistle/Models/Profile/Profile.swift
  Whistle/Models/Profile/User.swift
  Whistle/Models/Profile/UserPostFeed.swift
  Whistle/Models/Profile/UserProfile.swift
  Whistle/UI/Screens/Profile/APITestView.swift
  Whistle/UI/Screens/Profile/CustomAlbumListView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/ViewModels/PhotoViewModel.swift
  Whistle/ViewModels/UserViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#29 [Feat] AlamoFire async/await 처리, APIViewModel 내부 함수, Extension+Protocol 로 분리, 닉네임 중복, 변경 기간 관련 로직 적용 및 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Profile/APITestView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
  Whistle/Utilities/Extensions/APIViewModel+Upload.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/ViewModels/Protocols/ProfileProtocol.swift
  Whistle/ViewModels/Protocols/SettingProtocol.swift
  Whistle/ViewModels/Protocols/UploadProtocol.swift
  Whistle/ViewModels/UserViewModel.swift
Labels: feat

#31 [Feat] 테스트 뷰 삭제
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Profile/APITestView.swift
Labels: feat

#33 [Fix] 사진 업로드 시 앱 크래시 현상 수정
  Whistle/Resources/Assets.xcassets/Image/Profile/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Profile/ProfileDefault.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Profile/ProfileDefault.imageset/ProfileDefault.png
  Whistle/Resources/Assets.xcassets/Image/Profile/ProfileDefault.imageset/ProfileDefault@2x.png
  Whistle/Resources/Assets.xcassets/Image/Profile/ProfileDefault.imageset/ProfileDefault@3x.png
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
Labels: fix

#39 [Feat] 메인화면 영상 API 연동
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Profile/MainContent.swift
  Whistle/Models/VideoModel.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/PlayerPageView.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/ViewModels/VideoViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#41 [Feat] 내가 올린 영상 리스트 불러오기 구현
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Profile/MainContent.swift
  Whistle/Models/Profile/PostFeed.swift
  Whistle/Models/UserAuth.swift
  Whistle/Models/VideoModel.swift
  Whistle/UI/Screens/Main/Player.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/ReportUserView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/ViewModels/VideoViewModel.swift
Labels: feat

#43 [Feat] Glass moriphism border 방식 코드로 재수정, 프로필 삭제 기능 추가
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Profile/BookMark.swift
  Whistle/Models/Profile/PostFeed.swift
  Whistle/Models/Profile/Profile.swift
  Whistle/Models/Profile/ReportedContent.swift
  Whistle/Resources/Assets.xcassets/Image/Border/AlertBorder_UpdateID.imageset/AlertBorder_UpdateID.png
  Whistle/Resources/Assets.xcassets/Image/Border/AlertBorder_UpdateID.imageset/AlertBorder_UpdateID@2x.png
  Whistle/Resources/Assets.xcassets/Image/Border/AlertBorder_UpdateID.imageset/AlertBorder_UpdateID@3x.png
  Whistle/Resources/Assets.xcassets/Image/Border/AlertBorder_UpdateID.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/ProfileBorder.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/ProfileBorder.imageset/ProfileBorder.png
  Whistle/Resources/Assets.xcassets/Image/Border/ProfileBorder.imageset/ProfileBorder@2x.png
  Whistle/Resources/Assets.xcassets/Image/Border/ProfileBorder.imageset/ProfileBorder@3x.png
  Whistle/Resources/Assets.xcassets/Image/Border/SheetBorder.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/SheetBorder.imageset/SheetBorder.png
  Whistle/Resources/Assets.xcassets/Image/Border/SheetBorder.imageset/SheetBorder@2x.png
  Whistle/Resources/Assets.xcassets/Image/Border/SheetBorder.imageset/SheetBorder@3x.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabBarBorder.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/TabBarBorder.imageset/TabBarBorder.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabBarBorder.imageset/TabBarBorder@2x.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabBarBorder.imageset/TabBarBorder@3x.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabButtonBorder.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/Border/TabButtonBorder.imageset/TabButtonBorder.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabButtonBorder.imageset/TabButtonBorder@2x.png
  Whistle/Resources/Assets.xcassets/Image/Border/TabButtonBorder.imageset/TabButtonBorder@3x.png
  Whistle/UI/Components/Profile/ProfileAlert.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/ViewModels/Protocols/ProfileProtocol.swift
Labels: feat

#47 [Feat] 팔로우, 언팔로우 기능 구현
  Whistle/Models/Profile/Follow.swift
  Whistle/UI/Components/Profile/FollowButtonStyle.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
Labels: feat

#49 [Feat] Push notification 기능 세팅
  Whistle/Models/UserAuth.swift
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
  Whistle/ViewModels/Protocols/SettingProtocol.swift
  Whistle/Whistle.entitlements
  Whistle/WhistleApp.swift
Labels: feat

#51 [Feat] API (GET) 요청 횟수 줄이기 최적화
  Whistle/Models/Profile/Profile.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
Labels: feat

#53 [REFACTOR] uploadDeviceToken에 기기, os, 정보 추가
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
Labels: refactor

#55 Feat/#7 - 음원 다운로드 기능 완료
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Music/Music.swift
  Whistle/Models/Music/MusicService.swift
  Whistle/UI/Components/CircularProgressBar.swift
  Whistle/UI/Components/SearchBar.swift
  Whistle/UI/MusicListView.swift
  Whistle/UI/Screens/MusicListView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/Utilities/Extensions/APIViewModel+Music.swift
  Whistle/WhistleApp.swift
Labels: feat

#57 [FEAT] 음악 다운로드 및 재생 기능 구현 완료
  Whistle/UI/Components/CircularProgressBar.swift
  Whistle/UI/Components/SearchBar.swift
  Whistle/UI/Screens/MusicListView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/WhistleApp.swift
Labels: feat

#56 [REFACTOR] 기타 기능 개선(최적화) 및 디자인 요소 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/OffsetKey.swift
  Whistle/Models/PhotoModel.swift
  Whistle/UI/Components/Profile/ProfileAlert.swift
  Whistle/UI/Components/Profile/ProfileTabItem.swift
  Whistle/UI/Screens/Profile/CustomAlbumListView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/ViewModels/PhotoViewModel.swift
Labels: refactor

#64 [FEAT] 메인 뷰 및 기타 작업
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Enums.swift
  Whistle/Models/Profile/BookMark.swift
  Whistle/Models/Profile/MainContent.swift
  Whistle/Models/Profile/PostFeed.swift
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/Profile/DeleteAccountAlert.swift
  Whistle/UI/Components/Profile/ProfileToastMessage.swift
  Whistle/UI/Screens/Main/MainReportBottomSheet.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/PlayerPageView.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportReasonView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/ViewModels/PhotoViewModel.swift
  Whistle/ViewModels/Protocols/ProfileProtocol.swift
Labels: feat

#67 [Feat] 메인뷰 기타 수정사항 적용 (커밋 참조)
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Enums.swift
  Whistle/Models/Profile/MainContent.swift
  Whistle/Models/Profile/ReportedContent.swift
  Whistle/UI/Components/CancelableToastMessage.swift
  Whistle/UI/Components/Profile/DeleteAccountAlert.swift
  Whistle/UI/Components/Profile/ToastMessage.swift
  Whistle/UI/Screens/Main/MainReportBottomSheet.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/PlayerPageView.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/Report/ReportPostView.swift
  Whistle/UI/Screens/Profile/Report/ReportReasonView.swift
  Whistle/UI/Screens/Profile/Report/ReportUserView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/ViewModels/Protocols/ProfileProtocol.swift
Labels: feat

#72 [FIX] #58 - Bug Fix
  VideoPicker/VideoPicker/Editor/Controller/InputTextViewController.swift
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/UI/Components/Profile/DeleteAccountAlert.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
Labels: bug

#73 [Refactor] 여러 버그 수정 및 QA 적용 (커밋참조)
  Whistle.xcodeproj/project.pbxproj
  Whistle/Resources/Assets.xcassets/Image/DefaultBG.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/DefaultBG.imageset/DefaultBG.png
  Whistle/Resources/Assets.xcassets/Image/DefaultBG.imageset/DefaultBG@2x.png
  Whistle/Resources/Assets.xcassets/Image/DefaultBG.imageset/DefaultBG@3x.png
  Whistle/Resources/Assets.xcassets/Image/GoogleLogo.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/GoogleLogo.imageset/GoogleLogo.png
  Whistle/Resources/Assets.xcassets/Image/GoogleLogo.imageset/GoogleLogo@2x.png
  Whistle/Resources/Assets.xcassets/Image/GoogleLogo.imageset/GoogleLogo@3x.png
  Whistle/Resources/Fonts/Roboto-Medium.ttf
  Whistle/TestView.swift
  Whistle/UI/Components/ReportAlert.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/Player.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/Report/ReportPostView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/SignInView/SignInView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/WhistleApp.swift
Labels: refactor

#75 [Feat] BottomSheet custom에서 library로 변경, UserFollowView 데이터 저장 방식 변경
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
Labels: feat

#77 [FIX] 머지하면서 생긴 빌드 오류 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/TestView.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/WhistleApp.swift
Labels: fix

#79 [Refactor] 화면 탭이동 애니메이션 처리
  Whistle/UI/Screens/TabbarView.swift
  Whistle/WhistleApp.swift
Labels: refactor
