Repository WhistleGlobal/whistle-iOS, pull requests merged in 2023-10, with the labels that each got.

#81 Feat/#58 - [REFACTOR] PhotoPicker 프레임워크 리팩토링
  VideoPicker/VideoPicker/Core/Model/MediaType.swift
  VideoPicker/VideoPicker/Picker/Controller/AssetPickerViewController+Capture.swift
  VideoPicker/VideoPicker/Picker/Controller/AssetPickerViewController.swift
  VideoPicker/VideoPicker/Picker/Controller/PhotoPreviewController.swift
  VideoPicker/VideoPicker/Picker/Extension/Picker+MediaType.swift
  VideoPicker/VideoPicker/Picker/Extension/Picker+PHAsset.swift
  VideoPicker/VideoPicker/Picker/Model/Album.swift
  VideoPicker/VideoPicker/Picker/Model/Asset.swift
  VideoPicker/VideoPicker/Picker/PickerOptionsInfo.swift
  VideoPicker/VideoPicker/Picker/PickerTheme.swift
  VideoPicker/VideoPicker/Picker/Util/PickerManager+Photo.swift
  VideoPicker/VideoPicker/Picker/Util/PickerManager.swift
  VideoPicker/VideoPicker/Picker/View/Cell/AssetCell.swift
  VideoPicker/VideoPicker/Picker/View/Cell/CameraCell.swift
  VideoPicker/VideoPicker/Picker/View/Cell/PhotoGIFPreviewCell.swift
  VideoPicker/VideoPicker/Picker/View/PickerPreviewIndexView.swift
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Main/MainReportBottomSheet.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewController.swift
  Whistle/UI/Screens/VideoPicker/PickerPreviewCell.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/WhistleApp.swift
Labels: refactor

#85 [Refactor] 메인화면 비디오가 전부 로드되기전에도 동작하도록 수정, 다른사람 프로필 버그 수정
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/WhistleApp.swift
Labels: refactor

#86 Feat/#58 - Cut UI 완성
  VideoPicker/VideoPicker/Picker/Controller/ImagePickerController.swift
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/VideoEditor/EditableVideo.swift
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplictDark/Gray80_Dark.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/VideoEditor/Player/EditablePlayerView.swift
  Whistle/UI/Components/VideoEditor/Sliders/NewTimelineSlider.swift
  Whistle/UI/Components/VideoEditor/Sliders/RangeSliderView.swift
  Whistle/UI/Modifier/FontSystem.swift
  Whistle/UI/Screens/ToolsView/CutView/ThumbnailsSliderView.swift
  Whistle/UI/Screens/ToolsView/Speed/VideoSpeedSlider.swift
  Whistle/UI/Screens/ToolsView/ToolsSectionView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/CustomNavigationBarViewController.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/TimeLineView.swift
  Whistle/UI/Screens/VideoEditor/RootView/RootView.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewController.swift
  Whistle/Utilities/Extensions/Extension+Double.swift
  Whistle/Utilities/Extensions/Extension+UITableViewCell.swift
  Whistle/Utilities/Service/Player/VideoPlayerManager.swift
  Whistle/ViewModels/VideoEditor/ResizeViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#87 [FEAT] 프로필 화면 Sticky Header 기능 추가
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
Labels: feat

#90 [Feat] 조회수 로직 구현 (API 연동 제외)
  Whistle/UI/Screens/Main/MainView.swift
Labels: feat

#92 [Feat] 잔버그 QA (커밋참조)
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Main/Player.swift
  Whistle/UI/Screens/Main/PlayerPageView.swift
  Whistle/UI/Screens/Main/PlayerView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/NavigationUtil.swift
Labels: feat

#95 [Feat] 조회수 API 연동 구현
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/ViewCount.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
Labels: feat

#97 [FIX] 조회수 API 함수가 userid를 보내지 않도록 수정
  Whistle/Models/ViewCount.swift
Labels: fix

#99 [Feat] 비로그인 API 연동 및 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Profile/NoSignInMainContent.swift
  Whistle/UI/Screens/NoSignIn/NoSignInMainView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
Labels: feat

#102 [Feat] 프로필 사진 변경 갤러리 최적화
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Profile/ProfilePhoto/CachedImageManager.swift
  Whistle/Models/Profile/ProfilePhoto/PhotoAsset.swift
  Whistle/Models/Profile/ProfilePhoto/PhotoAssetCollection.swift
  Whistle/Models/Profile/ProfilePhoto/PhotoCollection.swift
  Whistle/Models/Profile/ProfilePhoto/PhotoLibrary.swift
  Whistle/UI/Screens/Profile/CustomAlbumListView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/ViewModels/PhotoViewModel.swift
Labels: feat

#104 [FEAT] #103 메인 뷰 기능추가 더블탭, 롱탭
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
Labels: feat

#105 [Feat] Universal link 구현
  Whistle/Models/Profile/Profile.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/ViewModels/Protocols/PostFeedProtocol.swift
  Whistle/Whistle.entitlements
  Whistle/WhistleApp.swift
  Whistle/WhistleDebug.entitlements
Labels: feat

#106 Feat/#58 - 음악 편집 기능 구현
  VideoPicker/VideoPicker/Capture/Controller/PadCaptureViewController.swift
  VideoPicker/VideoPicker/Picker/Controller/AlbumPickerViewController.swift
  VideoPicker/VideoPicker/Picker/Controller/AssetPickerViewController.swift
  VideoPicker/VideoPicker/Picker/Extension/Picker+UIScreen.swift
  VideoPicker/VideoPicker/Picker/View/Cell/AlbumCell.swift
  VideoPicker/VideoPicker/Picker/View/Kit/PickerArrowButton.swift
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/VideoEditor/EditableVideo.swift
  Whistle/Models/VideoEditor/ToolModel.swift
  Whistle/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Whistle/Resources/Assets.xcassets/AppIcon.appiconset/logo-whistle-noalpha.png
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplictDark/Gray40_Dark.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/SearchBar.swift
  Whistle/UI/Components/VideoEditor/Buttons/ToolButtonView.swift
  Whistle/UI/Components/VideoEditor/Player/EditablePlayerView.swift
  Whistle/UI/Components/VideoEditor/Sliders/CustomSlider.swift
  Whistle/UI/Components/VideoEditor/Sliders/RangeSliderView.swift
  Whistle/UI/Screens/MusicListView.swift
  Whistle/UI/Screens/MusicTrimView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/ToolsView/CutView/ThumbnailsSliderView.swift
  Whistle/UI/Screens/ToolsView/Speed/VideoSpeedSlider.swift
  Whistle/UI/Screens/ToolsView/ToolsSectionView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/CustomNavigationBarViewController.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoPicker/ConfigCell.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewController.swift
  Whistle/UI/Screens/VideoPicker/PickerPreviewCell.swift
  Whistle/UI/Screens/VideoPicker/PickerResultViewController.swift
  Whistle/UI/Screens/VideoPicker/VideoPickerTestView.swift
  Whistle/Utilities/Extensions/Extension+AVAudioSession.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/Utilities/Service/Player/VideoPlayerManager.swift
  Whistle/ViewModels/MusicViewModel.swift
  Whistle/ViewModels/VideoEditor/EditorViewModel.swift
  Whistle/WhistleApp.swift
Labels: feat

#114 [Refactor] 기타 버그 수정 & QA
  Whistle/UI/Components/Profile/FollowButtonStyle.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/SEUserProfileView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
Labels: refactor

#116 Feat/#58 - 해시태그 완료
  Whistle.xcodeproj/project.pbxproj
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplicitLight/Gray10_Light.colorset/Contents.json
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplicitLight/Gray20_Light.colorset/Contents.json
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplicitLight/Gray40_Light.colorset/Contents.json
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplicitLight/Gray60_Light.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/SearchBar.swift
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/ToolsView/CutView/ThumbnailsSliderView.swift
  Whistle/UI/Screens/Upload/Tags.swift
  Whistle/UI/Screens/Upload/TagsContent.swift
  Whistle/UI/Screens/Upload/TagsDataModel.swift
  Whistle/UI/Screens/Upload/TagsViewModel.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/CustomNavigationBarViewController.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewController.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewControllerWrapper.swift
  Whistle/Utilities/Extensions/APIViewModel+Upload.swift
Labels: feat

#118 [Feat] 카메라 구현
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/UI/BottomSheetTestView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/UI/Screens/VideoView/GalleryView.swift
  Whistle/UI/Screens/VideoView/PhotoAssetModel.swift
  Whistle/UI/Screens/VideoView/PhotoFile.swift
  Whistle/UI/Screens/VideoView/Video Asset.swift
  Whistle/UI/Screens/VideoView/VideoConentViewModel.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/UI/Screens/VideoView/VideoFile.swift
  Whistle/UI/Screens/VideoView/VideoSettingView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
Labels: feat

#120 [REFACTOR] 다크모드 대응 수정
  Whistle/UI/Screens/Profile/CustomPhotoView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
Labels: refactor

#123 Feat/#117 - API 연동 완료
  VideoPicker/VideoPicker/Picker/Controller/ImagePickerController.swift
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/VideoEditor/EditableVideo.swift
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/Music/MusicTrimView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/ToolsView/CutView/ThumbnailsSliderView.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/VideoExporterBottomSheetView.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewController.swift
  Whistle/UI/Screens/VideoPicker/PickerConfigViewControllerWrapper.swift
  Whistle/Utilities/Extensions/APIViewModel+Upload.swift
  Whistle/Utilities/Extensions/Extension+AVAssets.swift
  Whistle/Utilities/Helpers/VideoEditor.swift
  Whistle/ViewModels/MusicViewModel.swift
  Whistle/ViewModels/Protocols/UploadProtocol.swift
  Whistle/ViewModels/VideoEditor/EditorViewModel.swift
  Whistle/ViewModels/VideoEditor/ExporterViewModel.swift
Labels: feat

#124 [Refactor] 강제 업데이트 추가 (앱스토어 버전 체크 후 자체 API 호출을 자주 하지 않도록만 구현)
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/VersionCheck.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/SignInView/SignInView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Setting.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/ViewModels/Protocols/SettingProtocol.swift
  Whistle/WhistleApp.swift
Labels: refactor

#126 [FEAT] #125 업로드 갤러리 .sheet 화면 연결 버그 수정
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Helpers/VideoEditor.swift
Labels: feat

#127 [Refactor] 해시태그 데이터 타입 [String] 으로 수정
  Whistle/Models/Profile/MainContent.swift
  Whistle/Models/Profile/PostFeed.swift
  Whistle/Models/VersionCheck.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
Labels: refactor

#129 [Refactor] QA 수정사항 반영
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/AlbumModel.swift
  Whistle/Models/Profile/Follow.swift
  Whistle/Models/Profile/ProfilePhoto/PhotoCollection.swift
  Whistle/Models/Profile/UserPostFeed.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInMainView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/PhotoCollectionView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/SignInView/SignInView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
Labels: refactor

#131 [REFACTOR] #130 북마크 프로필 표시 버그 수정, 업로드 컨텐츠가 없을 ㅣ시 앱이 죽는 버그 수정
  Whistle/UI/Screens/Profile/MyBookmarkView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
Labels: refactor

#133 [Refactor] 업로드 QA 14, 16, 17, 18 번
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: refactor

#135 Feat/#117 - VideoContentView 수정
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/ViewModels/VideoEditor/ExporterViewModel.swift
Labels: feat

#137 [FEAT] #136 - 음악 선택 뷰 붙이기
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: feat

#138 [FEAT] #136 - 촬영한 비디오 가공하기
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/Models/VideoEditor/EditableVideo.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoView/VideoConentViewModel.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Extensions/Extension+AVAssets.swift
  Whistle/ViewModels/VideoEditor/EditorViewModel.swift
Labels: feat

#141 [FEAT] #136 - 비디오 촬영 후 즉시 업로드 기능 합체 완료
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/Music/MusicTrimView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoEditor/EditorView/PlayerHolderView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Service/Player/VideoPlayerManager.swift
Labels: feat

#142 [Refactor] QA 수정사항 반영 (15, 32 + 𝛂)
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/Report/ReportReasonView.swift
  Whistle/UI/Screens/Profile/Report/ReportUserView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: refactor

#144 Feat/#143 - Alert, 음악 버튼 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplictDark/Gray60_Dark.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Components/AlertPopup.swift
  Whistle/UI/Screens/VideoEditor/EditorView/MainEditorView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/WhistleApp.swift
Labels: feat

#148 [Refactor] 심사를 위한 수정, QA 반영
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/Enums.swift
  Whistle/Resources/Assets.xcassets/Image/gestureGuide.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/gestureGuide.imageset/gestureGuide.png
  Whistle/Resources/Assets.xcassets/Image/gestureGuide.imageset/gestureGuide@2x.png
  Whistle/Resources/Assets.xcassets/Image/gestureGuide.imageset/gestureGuide@3x.png
  Whistle/Resources/Assets.xcassets/Image/testCat.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/testCat.imageset/testCat.png
  Whistle/Resources/Assets.xcassets/Image/whistleLogo.imageset/whistleLogo.png
  Whistle/Resources/Assets.xcassets/Image/whistleLogo.imageset/whistleLogo@2x.png
  Whistle/Resources/Assets.xcassets/Image/whistleLogo.imageset/whistleLogo@3x.png
  Whistle/UI/Components/NotionWebView.swift
  Whistle/UI/Screens/ContentView.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInMainView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInProfileView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/MyBookmarkView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/PhotoCollectionView.swift
  Whistle/UI/Screens/Profile/PrivacyPolicyView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/SEProfileView.swift
  Whistle/UI/Screens/Profile/TermsOfServiceView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/Upload/TagsContent.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/Extension+View.swift
Labels: refactor

#151 [CHORE] #145 - tabbar 색상 변경
  Whistle/Resources/Assets.xcassets/Color/GrayColor/ExplicitLight/Gray80_Dark.colorset/Contents.json
  Whistle/Resources/Colors/ColorManager.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
Labels: chore

#152 [Refactor] 1차 심사전 찐막
  Whistle.xcodeproj/project.pbxproj
  Whistle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Whistle/UI/Components/AlertPopup.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/PhotoCollectionView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
Labels: refactor

#153 [CHORE] #145 - 필요없는 import 삭제
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/TermsOfServiceView.swift
Labels: chore

#154 [FEAT] #145 - Video capture session lifecycle 해결
  Aespa/Aespa.swift
  Whistle/UI/Screens/VideoView/VideoConentViewModel.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: feat

#156 [REFACTOR] #155 심사전 찐찐막
  Whistle/UI/Components/Profile/FollowButtonStyle.swift
  Whistle/UI/Components/Profile/FollowTabbarStyle.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
Labels: refactor

#159 [Refactor] 심사전 찐찐찐찐막 QA 수정
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/MyBookmarkView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
Labels: refactor

#160 Feat/#145 - QA 3개 해결
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/SEProfileView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: feat

#165 [Feat] 유저 차단 관련 수정, 메인 리로드 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/Models/BlockList.swift
  Whistle/Models/Profile/UserProfile.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/APIViewModel+PostFeed.swift
  Whistle/Utilities/Extensions/APIViewModel+Profile.swift
  Whistle/ViewModels/Protocols/ProfileProtocol.swift
Labels: feat

#166 Fix/164 - 앨범 커버가 표시되지 않는 문제 해결
  Aespa/Core/Representable/Photos+AespaRepresentable.swift
  Whistle/Resources/Assets.xcassets/Image/noVideo.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/noVideo.imageset/noVideo@1x.png
  Whistle/Resources/Assets.xcassets/Image/noVideo.imageset/noVideo@2x.png
  Whistle/Resources/Assets.xcassets/Image/noVideo.imageset/noVideo@3x.png
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
Labels: fix

#174 Refactor/#173 - 레이아웃 수정
  Whistle.xcodeproj/project.pbxproj
  Whistle/UI/Components/AlertPopup.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/Utilities/Extensions/Extension+UINavigationController.swift
Labels: refactor

#176 [REFACTOR] 타이머 버그 수정, tabbarviewmodel, apiviewmodel 싱글톤으로 변경
  Whistle/Models/UserAuth.swift
  Whistle/UI/Screens/Main/MainReportBottomSheet.swift
  Whistle/UI/Screens/Main/MainView.swift
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/Music/MusicTrimView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInMainView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInProfileView.swift
  Whistle/UI/Screens/Profile/FollowView.swift
  Whistle/UI/Screens/Profile/GlassBottomSheet.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportDetailView.swift
  Whistle/UI/Screens/Profile/MainReport/MainReportReasonView.swift
  Whistle/UI/Screens/Profile/MyBookmarkView.swift
  Whistle/UI/Screens/Profile/MyContentListView.swift
  Whistle/UI/Screens/Profile/PhotoCollectionView.swift
  Whistle/UI/Screens/Profile/ProfileEditIDView.swift
  Whistle/UI/Screens/Profile/ProfileEditIntroduceView.swift
  Whistle/UI/Screens/Profile/ProfileEditView.swift
  Whistle/UI/Screens/Profile/ProfileInfoView.swift
  Whistle/UI/Screens/Profile/ProfileNotiView.swift
  Whistle/UI/Screens/Profile/ProfileReportView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/Report/ReportDetailView.swift
  Whistle/UI/Screens/Profile/Report/ReportPostView.swift
  Whistle/UI/Screens/Profile/Report/ReportReasonView.swift
  Whistle/UI/Screens/Profile/Report/ReportUserView.swift
  Whistle/UI/Screens/Profile/SEProfileView.swift
  Whistle/UI/Screens/Profile/SEUserProfileView.swift
  Whistle/UI/Screens/Profile/UserContentListView.swift
  Whistle/UI/Screens/Profile/UserFollowView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/SignInView/SignInView.swift
  Whistle/UI/Screens/TabbarView.swift
  Whistle/UI/Screens/Upload/UploadView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/ViewModels/APIViewModel.swift
  Whistle/WhistleApp.swift
Labels: refactor

#178 [REFACTOR] #175 비로그인 시 메인에 게시물이 없을 시 에러가 나던 버그 수정
  Whistle/UI/Screens/NoSignIn/NoSignInMainView.swift
Labels: refactor

#179 Refactor/#177 - 카메라 기능 및 오류 수정
  Aespa/Core/Context/AespaVideoContext.swift
  Aespa/Core/Representable/AVCaptureDevice+AespaRepresentable.swift
  Aespa/View/InteractivePreview.swift
  Aespa/View/Preview.swift
  Whistle/Resources/Assets.xcassets/Image/BlurredDefaultBG.imageset/Contents.json
  Whistle/Resources/Assets.xcassets/Image/BlurredDefaultBG.imageset/blurredBG.png
  Whistle/UI/Components/Profile/DeleteAccountAlert.swift
  Whistle/UI/Components/Profile/ProfileAlert.swift
  Whistle/UI/Components/ReportAlert.swift
  Whistle/UI/Components/SignoutAlert.swift
  Whistle/UI/Screens/Music/MusicListView.swift
  Whistle/UI/Screens/NoSignIn/NoSignInProfileView.swift
  Whistle/UI/Screens/Profile/ProfileView.swift
  Whistle/UI/Screens/Profile/SEProfileView.swift
  Whistle/UI/Screens/Profile/SEUserProfileView.swift
  Whistle/UI/Screens/Profile/UserProfileView.swift
  Whistle/UI/Screens/VideoView/AccessView.swift
  Whistle/UI/Screens/VideoView/AlbumAccessView.swift
  Whistle/UI/Screens/VideoView/VideoContentView.swift
  Whistle/UI/Screens/VideoView/VideoContentViewModel.swift
  Whistle/Utilities/Extensions/Extension+UIVisualEffectView.swift
  Whistle/Utilities/Extensions/Extension+View.swift
  Whistle/Utilities/Service/Player/VideoPlayerManager.swift
  Whistle/ViewModels/VideoEditor/EditorViewModel.swift
  Whistle/ViewModels/VideoEditor/ExporterViewModel.swift
Labels: refactor, feat
